class Config():
    SQLALCHEMY_DATABASE_URI = environ.get("ULR_DATABASE_DEV") 
    if SQLALCHEMY_DATABASE_URI and SQLALCHEMY_DATABASE_URI.startswith('mysql:'):
        SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI.replace('mysql:', 'mysql+pymysql:')
    SQLALCHEMY_TRACK_MODIFICATIONS=False